#### Numpy

In [1]:
import numpy as np

In [2]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [3]:
two_d = np.array([range(i, i + 3) for i in [2, 4, 6]])

In [4]:
two_d[1:, 0:2]

array([[4, 5],
       [6, 7]])

In [5]:
two_d[:2, 1:]

array([[3, 4],
       [5, 6]])

In [6]:
two_dx2 = two_d * 2
two_dx2

array([[ 4,  6,  8],
       [ 8, 10, 12],
       [12, 14, 16]])

In [7]:
np.concatenate((two_d, two_dx2))

array([[ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 4,  6,  8],
       [ 8, 10, 12],
       [12, 14, 16]])

In [8]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
my_ndarray = np.array([[2,3,4],[5,7,12],[10,1,3],[7,2,5]])

In [10]:
my_ndarray

array([[ 2,  3,  4],
       [ 5,  7, 12],
       [10,  1,  3],
       [ 7,  2,  5]])

In [11]:
my_ndarray.T

array([[ 2,  5, 10,  7],
       [ 3,  7,  1,  2],
       [ 4, 12,  3,  5]])

In [12]:
x = np.arange(1,6)
print(x)
np.add.reduce(x)

[1 2 3 4 5]

np.int64(15)

In [13]:
np.min(my_ndarray)
np.max(my_ndarray)
np.sum(my_ndarray)
np.multiply.reduce(x)
my_ndarray.sum()
np.multiply.reduce(my_ndarray)

array([700,  42, 720])

#### Computation on arrays

In [14]:
my_ndarray_t = my_ndarray.T
my_ndarray_t

array([[ 2,  5, 10,  7],
       [ 3,  7,  1,  2],
       [ 4, 12,  3,  5]])

In [15]:
my_ndarray * my_ndarray

array([[  4,   9,  16],
       [ 25,  49, 144],
       [100,   1,   9],
       [ 49,   4,  25]])

#### Dog Product

In [16]:
new_ar = np.random.random((3,3))
new_ar.dot(my_ndarray.T)
new_ar.shape
my_ndarray.shape

(4, 3)

In [17]:
# Numpy array with shape 3 by 3 having data ranging from 0 to 8

In [18]:
import numpy as np
np.array([range(i, i + 3) for i in [0, 3, 6]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
matrix = np.arange(9).reshape(3,3)

In [20]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
# replace all odd numbers with -1
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])
#arr[arr % 2 == 1] = -1
#print numbers greater than 7
arr[arr > 7]

array([ 8,  9, 10, 11])

### Pandas

In [22]:
import pandas as pd

In [23]:
data = pd.Series([0.25,0.5,0.75,1.0])

In [24]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [25]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [26]:
data[:2]

0    0.25
1    0.50
dtype: float64

In [27]:
data = pd.Series({2: 'a', 3: 'b', 4: 'c'})

In [28]:
data

2    a
3    b
4    c
dtype: object

##### Creating a pandas framework

In [29]:
import pandas as pd

data_dict = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Kenneth', 'Sandra'],
    'Age': [24, 27, 22, 35, np.nan],
    'City': ['Edo', 'Ibadan', 'Warri', 'Edo', np.nan]
}
df = pd.DataFrame(data_dict)
df

      Name   Age    City
0    Alice  24.0     Edo
1      Bob  27.0  Ibadan
2  Charlie  22.0   Warri
3  Kenneth  35.0     Edo
4   Sandra   NaN     NaN

In [30]:
print(type(pd.DataFrame))

<class 'type'>

###### filter database on certain conditions

In [31]:
filtered_df = df[(df['Age'] > 30) & (df['City'] == 'Edo')]

In [32]:
df['Age'].sum()

np.float64(108.0)

In [33]:
df['Age'].mean()

np.float64(27.0)

In [34]:
df['Math score'] = [70, 32, 58, 81, 60]
df

      Name   Age    City  Math score
0    Alice  24.0     Edo          70
1      Bob  27.0  Ibadan          32
2  Charlie  22.0   Warri          58
3  Kenneth  35.0     Edo          81
4   Sandra   NaN     NaN          60

In [35]:
df['English score'] = [85, 81, 73, 92, 70]
df['Score'] = (df['Math score'] + df['English score']) / 2
df

      Name   Age    City  Math score  English score  Score
0    Alice  24.0     Edo          70             85   77.5
1      Bob  27.0  Ibadan          32             81   56.5
2  Charlie  22.0   Warri          58             73   65.5
3  Kenneth  35.0     Edo          81             92   86.5
4   Sandra   NaN     NaN          60             70   65.0

In [36]:
df.iloc[0:5, 3:5] + 10

   Math score  English score
0          80             95
1          42             91
2          68             83
3          91            102
4          70             80

### Data Cleaning

In [37]:
mean_age = df['Age'].mean()
df['Age'] = df['Age'].fillna(mean_age)
df

      Name   Age    City  Math score  English score  Score
0    Alice  24.0     Edo          70             85   77.5
1      Bob  27.0  Ibadan          32             81   56.5
2  Charlie  22.0   Warri          58             73   65.5
3  Kenneth  35.0     Edo          81             92   86.5
4   Sandra  27.0     NaN          60             70   65.0

In [38]:
fill_city = 'Lagos'
df['City'] = df['City'].fillna(fill_city)
df

      Name   Age    City  Math score  English score  Score
0    Alice  24.0     Edo          70             85   77.5
1      Bob  27.0  Ibadan          32             81   56.5
2  Charlie  22.0   Warri          58             73   65.5
3  Kenneth  35.0     Edo          81             92   86.5
4   Sandra  27.0   Lagos          60             70   65.0

In [40]:
data = pd.Series([1,np.nan,'hello',None])

In [41]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [42]:
data.dropna()

0        1
2    hello
dtype: object

In [43]:
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [44]:
df = pd.DataFrame([[1,np.nan,2], [2,3,5], [np.nan, 4, 6]])
df

     0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [55]:
df[3] = 9
df[4] = [5, np.nan, 6]
df

     0    1  2  3    4
0  1.0  NaN  2  9  5.0
1  2.0  3.0  5  9  NaN
2  NaN  4.0  6  9  6.0

In [56]:
df.dropna(axis= 1)

   2  3
0  2  9
1  5  9
2  6  9

In [57]:
df.fillna(0)

     0    1  2  3    4
0  1.0  0.0  2  9  5.0
1  2.0  3.0  5  9  0.0
2  0.0  4.0  6  9  6.0

In [59]:
df.ffill()

     0    1  2  3    4
0  1.0  NaN  2  9  5.0
1  2.0  3.0  5  9  5.0
2  2.0  4.0  6  9  6.0